name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      # - main
      - debugging_1

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up QEMU for multi-platform builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Set up Docker Buildx 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
 
    # Log in to Azure Container Registry using credentials stored in GitHub Secrets
    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # Build and push Docker image to Azure Container Registry
    - name: Build and push Docker image
      run: |
        DATE_TAG=$(date +"%Y%m%d_%H%M%S")
        REGISTRY=${{ secrets.ACR_REGISTRY }}
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/hello-world1:DATE_TAG . --build-arg AZ_ACCESS_KEY=${{ secrets.AZ_ACCESS_KEY }}
        docker tag ${{ secrets.ACR_LOGIN_SERVER }}/hello-world1:DATE_TAG REGISTRY.azurecr.io/hello-world1:DATE_TAG
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/hello-world1:DATE_TAG

    # Deploy the Docker image from ACR to Azure Web App
    - name: Azure Web App deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hello-world1'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.ACR_LOGIN_SERVER }}/hello-world1:DATE_TAG'
